# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f836fe881edb12f185515a45d2e8bbe29dd8d015f3f21063fab92d5bd40b14998ac3327f424aae7f2f38e24d93c521481ad6fa83695674a2addb8be018f17d2

test:
  secret_key_base: 939b4a019dde302da2578021afd1662db1847ec6a8fe99c3299203ca5eb8d7222674514926bbeb3a370bb2c5d9884759d09cf65651c10b003a8b4a425e07f5b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
